### ISSUE TITLE
Sitemap adding error

### ISSUE THREAD

**Issue by thanhnguyenthew** [utopigstudio/octobercms-plugin-seo#18]
After updated the plugins to 1.1.8, the Sitemap function is not working. It only adds empty data in to the database which returns error when I tried to edit

![image](https://user-images.githubusercontent.com/77180062/139826419-47cd7bde-e7ca-48a0-a708-a8d2145e0bd0.png)
![image](https://user-images.githubusercontent.com/77180062/139826223-869248c5-218e-4159-b8ce-9bc8f212a5e5.png)
![image](https://user-images.githubusercontent.com/77180062/139826267-a75d6ac4-f9b6-43ef-8b2a-e3bc7b38d524.png)

I think I could add sitemap without problem in 1.1.7 so please fix this soon

**Comment by mariavilaro** [comment]
Fixed! It was not a problem with 1.1.8, but with October 2 changes, when you tried to add an item, it was not correctly saved.
