### ISSUE TITLE
Generated sitemap stop working

### ISSUE THREAD

**Issue by willouch** [utopigstudio/octobercms-plugin-seo#5]
Hi,

After update, generated sitemap.xml is in line texte, And google stop validated sitemap.xml

Thks

Sorry its come back....

**Comment by willouch** [comment]
Sorry its come back....

**Comment by mariavilaro** [comment]
Hi! google should validate sitemap.xml now. Right now is not possible to have sitemap.xml correctly parsed by browsers AND by google. So another sitemap is generated on sitemap-debug.xml so you can check it with a browser.  For example: https://utopigstudio.com/sitemap-debug.xml

**Comment by willouch** [comment]
Thks you are the BEST!!!

I have finish the most important french translation, I test it in prod and i send to you the package if you want???
